### ISSUE TITLE
Unable to Open Demo Map

### ISSUE THREAD

**Issue by vp5h** [MaximeDup/FaceCaptureUnrealEngine#1]
Below is the Error, I got 
"Failed to open map file. This is most likely because the map was saved with a newer version of the engine."

Tried the Project with 4.26.2 
and 4.25 Source Build
Got the same error.

May be Having the same version would solve the Erorr.

**Comment by MaximeDup** [comment]
Oh damn, this comes from using 4.26.2 chaos source. Let me fix this

**Comment by MaximeDup** [comment]
Solved

**Comment by vp5h** [comment]
Thanks, Man!
