### ISSUE TITLE
BP_Points_To_BlendWeights not in project

### ISSUE THREAD

**Issue by rphad23** [MaximeDup/FaceCaptureUnrealEngine#4]
the BP_Points_To_BlendWeights is not even in the project anymore. How is one supposed to use this if the most important BP does not exist?

**Comment by rforman9** [comment]
@rphad23 That Blueprint is still in the project.  The actual blueprint file is BP_BlendshapesHandler.  He renamed the instance BP_Points_To_Blendweights after bringing it into his project.
![image](https://user-images.githubusercontent.com/12390721/167043718-7332057a-e5f3-4388-95d5-a658bf494deb.png)
