### ISSUE TITLE
Distanceinfluence blendshape parameter does not seem to be getting applied

### ISSUE THREAD

**Issue by rforman9** [MaximeDup/FaceCaptureUnrealEngine#5]
https://github.com/MaximeDup/FaceCaptureUnrealEngine/blob/c159662643f4fd4bc6069dd3fc186abb39966991/Source/AndroidFaceCapture/Private/EditorTickingActors.cpp#L66

I tried uncommenting the above line, but I saw no visible difference in the data curves coming into livelink unless I changed the value to 0.  Why is this line commented out?  Should the distance influence parameter work without it?

**Comment by MaximeDup** [comment]
It allows to make some point more important than other, i ended up disabling it as there were no proper interface to manage it gracefully anyway.
