### ISSUE TITLE
ERROR: Unable to find plugin 'TcpSocketPlugin' 

### ISSUE THREAD

**Issue by lucasjinreal** [MaximeDup/FaceCaptureUnrealEngine#6]
Hi, do u know how to make this plugin open?

ERROR: Unable to find plugin 'TcpSocketPlugin'

Can not even using UE open it.

**Comment by MaximeDup** [comment]
It's a free plugin on unreal engine marketplace:
https://www.unrealengine.com/marketplace/en-US/product/tcp-socket-plugin
